# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cz7ww1dcs-capi-aws
  namespace: cz7ww1dcs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cz7ww1dcs-capi-aws
subjects:
- kind: ServiceAccount
  name: cz7ww1dcs-capi-aws
